# =============================================================================
# CONFIGURATION DJANGO (course_service/settings.py)
# =============================================================================
# Ce fichier contient toutes les configurations du projet Django
# Il définit les paramètres pour la base de données, les applications, la sécurité, etc.

"""
Django settings for course_service project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# =============================================================================
# IMPORTS
# =============================================================================
from pathlib import Path  # Pour manipuler les chemins de fichiers de manière portable

# =============================================================================
# CONFIGURATION DES CHEMINS
# =============================================================================
# Construire les chemins à l'intérieur du projet comme ceci: BASE_DIR / 'subdir'.
# BASE_DIR pointe vers le répertoire racine du projet Django
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# CONFIGURATION DE SÉCURITÉ
# =============================================================================
# ATTENTION: Ces paramètres sont pour le développement - ne pas utiliser en production !

# Clé secrète utilisée pour le chiffrement des sessions et autres données sensibles
# ⚠️ IMPORTANT: En production, utilisez une clé secrète différente et gardez-la secrète !
SECRET_KEY = 'django-insecure-z&q2eq@7goqn0_0)b%w2(l1jnd3qq(*^*m^jj+@cj9$5#6gfk8'

# Mode debug : affiche les erreurs détaillées en cas de problème
# ⚠️ ATTENTION: Toujours mettre à False en production !
DEBUG = True

# Liste des hôtes autorisés à accéder à l'application
# En développement, on peut laisser vide pour accepter toutes les connexions
ALLOWED_HOSTS = []

# =============================================================================
# CONFIGURATION DES APPLICATIONS
# =============================================================================
# Liste de toutes les applications Django installées dans ce projet

INSTALLED_APPS = [
    # Applications Django par défaut
    'django.contrib.admin',        # Interface d'administration Django
    'django.contrib.auth',         # Système d'authentification Django
    'django.contrib.contenttypes', # Framework de types de contenu
    'django.contrib.sessions',     # Gestion des sessions utilisateur
    'django.contrib.messages',     # Système de messages
    'django.contrib.staticfiles',  # Gestion des fichiers statiques (CSS, JS, images)
    'rest_framework.authtoken' ,
    
    # Applications tierces pour l'API REST
    'rest_framework',              # Django REST Framework pour créer des APIs
    'django_filters',              # Filtrage avancé pour les APIs
    'django_extensions',
    # Application locale
    'course',        
    
                    # Notre application pour gérer les cours et étudiants
]

# =============================================================================
# CONFIGURATION DJANGO REST FRAMEWORK
# =============================================================================
# Configuration spécifique à Django REST Framework pour l'API

REST_FRAMEWORK = {
    # Backend de filtrage par défaut pour toutes les APIs
    # DjangoFilterBackend permet le filtrage exact par champs
  
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.TokenAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],


}

# =============================================================================
# CONFIGURATION DU MICROSERVICE STUDENT SERVICE
# =============================================================================
# Paramètres pour la communication avec le microservice Spring Boot

# URL de base du microservice Student Service
# Cette URL doit correspondre à l'URL de votre service Spring Boot
STUDENT_SERVICE_URL = 'http://localhost:8081/api/students'

# Timeout pour les appels HTTP vers le microservice (en secondes)
# Si le microservice ne répond pas dans ce délai, l'appel sera annulé
STUDENT_SERVICE_TIMEOUT = 5
# =============================================================================
# CONFIGURATION DES MIDDLEWARES
# =============================================================================
# Les middlewares sont des composants qui traitent les requêtes HTTP
# avant qu'elles n'atteignent les vues et les réponses avant qu'elles ne soient renvoyées

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # Sécurité générale
    'django.contrib.sessions.middleware.SessionMiddleware',   # Gestion des sessions
    'django.middleware.common.CommonMiddleware',               # Fonctionnalités communes
    'django.middleware.csrf.CsrfViewMiddleware',               # Protection CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Authentification
    'django.contrib.messages.middleware.MessageMiddleware',     # Système de messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   # Protection contre le clickjacking
]

# =============================================================================
# CONFIGURATION DES URLS ET TEMPLATES
# =============================================================================
# Fichier principal de configuration des URLs
ROOT_URLCONF = 'course_service.urls'

# Configuration des templates (fichiers HTML)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Moteur de templates Django
        'DIRS': [],  # Répertoires supplémentaires pour les templates
        'APP_DIRS': True,  # Chercher les templates dans les dossiers des applications
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',      # Objet request dans les templates
                'django.contrib.auth.context_processors.auth',     # Informations d'authentification
                'django.contrib.messages.context_processors.messages',  # Messages système
            ],
        },
    },
]

# =============================================================================
# CONFIGURATION WSGI
# =============================================================================
# Point d'entrée WSGI pour déployer l'application
WSGI_APPLICATION = 'course_service.wsgi.application'

# =============================================================================
# CONFIGURATION DE LA BASE DE DONNÉES
# =============================================================================
# Configuration de la base de données SQLite (par défaut pour le développement)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Moteur de base de données SQLite
        'NAME': BASE_DIR / 'db.sqlite3',         # Chemin vers le fichier de base de données
    }
}

# =============================================================================
# VALIDATION DES MOTS DE PASSE
# =============================================================================
# Validateurs pour s'assurer que les mots de passe sont sécurisés

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Vérifie que le mot de passe n'est pas trop similaire aux informations utilisateur
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # Vérifie que le mot de passe a une longueur minimale
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        # Vérifie que le mot de passe n'est pas dans la liste des mots de passe communs
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        # Vérifie que le mot de passe n'est pas entièrement numérique
    },
]

# =============================================================================
# CONFIGURATION INTERNATIONALE
# =============================================================================
# Paramètres pour la localisation et l'internationalisation

LANGUAGE_CODE = 'en-us'  # Langue par défaut (anglais américain)
TIME_ZONE = 'UTC'        # Fuseau horaire par défaut (UTC)
USE_I18N = True          # Activer l'internationalisation
USE_TZ = True            # Utiliser les fuseaux horaires

# =============================================================================
# CONFIGURATION DES FICHIERS STATIQUES
# =============================================================================
# Gestion des fichiers statiques (CSS, JavaScript, images)

STATIC_URL = 'static/'  # URL de base pour servir les fichiers statiques

# =============================================================================
# CONFIGURATION DES CLÉS PRIMAIRES
# =============================================================================
# Type de champ par défaut pour les clés primaires

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Clés primaires de type BigAutoField
CORS_ALLOW_ALL_ORIGINS = True
INSTALLED_APPS += ['corsheaders']
MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')